services:
  ocl-cache:
    #build: .
    image: ghcr.io/cheminfo/ocl-cache:v1.1.0
    restart: always
    ulimits:
      core: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./sqlite:/node/sqlite
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.oclcache.rule=Host(`ocl-cache.cheminfo.org`)'
      - 'traefik.http.routers.oclcache.entrypoints=websecure'
      - 'traefik.http.routers.oclcache.tls.certresolver=letsencrypt'

  process-sdf:
    #build: .
    image: ghcr.io/cheminfo/ocl-cache:v1.1.0
    restart: always
    ulimits:
      core: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./sqlite:/node/sqlite
      - ./data/sdf:/node/data/sdf
      - ./data/smiles:/node/data/smiles
    command: npm run processSDF

networks:
  traefik:
    external: true
