import { test, expect } from 'vitest';

import { getInfoFromSmiles } from '../getInfoFromSmiles';

test('getInfoFromSmiles', async () => {
  const result = await getInfoFromSmiles('CCOCC');
  expect(result).toMatchInlineSnapshot(`
    {
      "acceptorCount": 0,
      "atoms": "{\\"C\\":4,\\"H\\":10}",
      "charge": 0,
      "donorCount": 0,
      "em": 58.0782503223,
      "idCode": "gC\`@Dij@@",
      "logP": 1.8859999775886536,
      "logS": -1.5239999890327454,
      "mf": "C4H10",
      "mw": 58.12235112749877,
      "nbFragments": 1,
      "noStereoID": "gC\`@Dij@Os@",
      "noStereoTautomerID": "gC\`@Dij@@",
      "polarSurfaceArea": 0,
      "rotatableBondCount": 1,
      "ssIndex": [
        0,
        0,
        128,
        96,
        0,
        0,
        0,
        8,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
      ],
      "stereoCenterCount": 0,
      "unsaturation": 0,
    }
  `);
});
