name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: ocl-cache
  IMAGE_ID: ghcr.io/cheminfo/ocl-cache

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: npm
          registry-url: https://npm.pkg.github.com
      - name: Build image
        run: docker build . -f Dockerfile --build-arg NODE_VERSION=$(jq -r ".volta.node" package.json) --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        if: github.event_name != 'workflow_dispatch'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        if: github.event_name != 'workflow_dispatch'
        run: |
          docker tag $IMAGE_NAME $IMAGE_ID:${{ github.ref_name }}
          docker push $IMAGE_ID:${{ github.ref_name }}
